package com.binnacle.api.utils.errors;

public class ErrorDescriptions {
    public static final String RECORD_NOT_FOUND = "Requested record couldn't be found";
    public static final String EMPTY = "";
    public static final String NOT_BLANK = "This field cannot be blank";
    public static final String UP_TO_50_CHARACTERS = "This field cannot be blank";
    public static final String PROJECT_ALREADY_DEFINED = "This project name already exists";
    public static final String TASK_ALREADY_DEFINED = "This task name already exists";
    public static final String COULD_NOT_SAVE_PROJECT = "This project could no be saved";
    public static final String COULD_NOT_SAVE_TASK = "This task could no be saved";
    public static final String UPDATE_NOT_ALLOWED = "You cannot update this object";
    public static final String CREATION_NOT_ALLOWED = "Creation not allowed";
    public static final String DELETION_NOT_ALLOWED = "You cannot delete this object";
    public static final String ERROR_WHEN_RETREIVING_DATA = "Data couldnÂ´t be retreived";
    public static final String INVALID_PROJECT = "The project has not been found or is not owned by requester";
    public static final String TASK_NOT_FOUND = "The task has not been found";
    public static final String INVALID_TASK = "The task has not been found or is not owned by requester";
    public static final String TASK_RELATION_ERROR = "The task is not related to the given project";
    public static final String SUBTASK_NOT_FOUND = "The subtask has not been found";
    public static final String INVALID_SUBTASK = "The subtask has not been found or is not owned by requester";
    public static final String SUBTASK_RELATION_ERROR = "The subtask is not related to the given task";
}
